config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
	  root "notes#index", as: "authenticated_root"
  end

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord 
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  def index
    @notes = Note.where(user_id: current_user)
  end

  def new
  	@note = current_user.notes.build
  end

  def create
  	@note = current_user.notes.build(note_params)

  	if @note.save
  	  redirect_to @note
    else
      render 'new'
    end
  end

  def edit
  	
  end

  def update
  	if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'  
    end
  end

  def destroy
  	@note.destroy
    redirect_to notes_path
  end

  private

  def find_note
  	@note = Note.find(params[:id])
  end

  def note_params
  	params.require(:note).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
 <html>
   <head>
     <title>Notenote</title>
     <%= csrf_meta_tags %>

     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="manifest" href="/manifest.json" />
     <meta name="apple-mobile-web-app-capable" content="yes">
     <meta charset="UTF-8">
     <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#2E2F30"/>
  </head>

 <body>
  <header>
    <div class="header_inner">
      <%= link_to image_tag('logo.svg'), root_path, id: "logo" %>
      <nav>
        <% if user_signed_in? %>
          <%= link_to "New Note", new_note_path %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Log In", new_user_session_path %>
        <% end %>
      </nav>
    </div>
  </header>
  <p class="notice">
    <%= notice %>
  </p>
  <p class="alert">
    <%= alert %>
  </p>
  <%= yield  %>
</body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for @note do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/notes/edit.html.erb
<div class="wrapper_with_padding">
  <h1>Edit Your Note</h1>
  <%= render 'form' %>
  <%= link_to "Cancel", note_path %>
</div>

app/views/notes/index.html.erb
<div class="wrapper_with_padding">
  <notes class="clearfix">
    <% unless @notes.blank? %>
      <% @notes.each do |note| %>
        <a href="<%= (url_for [note]) %>">
          <div class="note">
            <p class="title">
              <%= note.title   %>
            </p>
            <p class="date">
              <%= time_ago_in_words(note.created_at) %>
            </p>
          </div>
        </a>
      <% end %>
    <% else  %>
      <h2>Add a note</h2>
      <p>It appears you haven't created any yet... Lets fix that. Why don't you create a new note below.</p>
      <button>
        <%= link_to "New Note", new_note_path %>
      </button>
    <% end %>
  </notes>
</div>

app/views/notes/new.html.erb
<div class="wrapper_with_padding">
  <h1>Add a new Note</h1>
  <%= render 'form' %>
</div>

app/views/notes/show.html.erb
<div class="wrapper_with_padding">
  <div id="note_show">
    <h1 class="title">
      <%= @note.title %>
    </h1>
    <p>
      <%= simple_format(@note.content) %>
    </p>
    <div class="buttons">
      <%= link_to "Edit", edit_note_path(@note), class: "button" %>
      <%= link_to "Delete", note_path(@note), method: :delete, data: {confirm: "Are you sure?"}, class: "button" %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1>NoteNote</h1>
    <p>Your online notebook. Never forget an idea again.</p>
    <button>
      <%= link_to "Sign Up", new_user_registration_path %>
    </button>
  </div>
</div>
<div id="bottom_cta">
  <div class="wrapper">
    <h2>For Realz!</h2>
    <button>
      <%= link_to "Click Meee!!!", new_user_registration_path %>
    </button>
  </div>
</div>
<footer>
  <p>&copy; SnowHoang</p>
</footer>